### ISSUE TITLE
Loading a PDF with highlighting/comments triggers an "undefined" citation count 

### ISSUE THREAD

**Issue by champagnealexandre** [eschnett/zotero-citationcounts#16]
Opening a PDF with highlighted text in an external PDF reader triggers an "undefined citation counts" in the new beta PDF reader in Zotero, which slows down loading the file a lot.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/30211986/135007945-884a2ad8-fda6-4c56-b1ad-e1d6805b107e.png">

**Comment by welpdx** [comment]
Hey @champagnealexandre,

This issue is fixed in my fork. Here are links to [download the add-on file](https://github.com/welpdx/zotero-citationcounts/releases/tag/v1.2.3) and [read more about it](https://github.com/welpdx/zotero-citationcounts). 

Please let me know if you happen upon any issues. 

Thanks!
Welp

---
For the author: this was [my fix](https://github.com/welpdx/zotero-citationcounts/commit/125654eb8899664b70acb1f485883509265fdbdb#r60475498). I'll learn how to do pulls requests one day.

**Comment by champagnealexandre** [comment]
@welpdx awesome! Just installed it and seems to work fine ; the plugin sometimes seems to update citation count when opening a pdf but only ONE time (I can live with that) instead of 562464 times like the old one did.

Thank you!

**Comment by welpdx** [comment]
@champagnealexandre, thanks for the feedback! I'm happy that the issue is solved. 

I couldn't replicate the minor issue you mentioned but if it bothers you in the future, just make an issue report. 

Thanks!
Welp

**Comment by champagnealexandre** [comment]
doesn’t bother me at all — the issue with the old version showing 5426 "citation updates" each time the pdf loaded was that zotero did sort of hang at that moment, but if it’s shown only 1 time there’s barely any effect

thank you!

**Comment by welpdx** [comment]
That's good hear thanks!
